[variables]
PYTHONUNBUFFERED = "1"

[phases.setup]
nixPkgs = ["python314", "uv"]

[phases.install]
dependsOn = ["setup"]
cmds = [
    "uv sync --frozen --no-dev",
]

[start]
cmd = "uv run python -m src.main daemon"
